### ISSUE TITLE
golrokh

### ISSUE THREAD

**Issue by kartx22** [sobhe/golrokh#1]
Hi golrokh was a nice program im interested on it can you explain me how it works?

**Comment by nournia** [comment]
Hi,
This repo is just a demo page, but if you want to find out about its algorithm, this paper helps you:

    Taigman, Yaniv, et al. "Deepface: Closing the gap to human-level performance in face verification." Computer Vision and Pattern Recognition (CVPR), 2014 IEEE Conference on. IEEE, 2014.

**Comment by kartx22** [comment]
thank you
